spring.application.name=vigszinhaz-monitor

spring.mail.username=${EMAIL_ADDRESS}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

vigszinhaz.monitor.url=https://vigszinhaz.jegy.hu/program/a-pal-utcai-fiuk-67954
vigszinhaz.monitor.interval=600000
vigszinhaz.monitor.initial-delay=0
vigszinhaz.monitor.request-timeout=60000
vigszinhaz.notification.recipient=nagavo@gmail.com
vigszinhaz.notification.subject=Vígszínház - új időpont