spring.application.name=vigszinhaz-monitor

resend.api-key=${RESEND_API_KEY}
resend.from=${RESEND_FROM}

vigszinhaz.monitor.url=https://vigszinhaz.jegy.hu/program/a-pal-utcai-fiuk-67954
vigszinhaz.monitor.interval=300000
vigszinhaz.monitor.initial-delay=0
vigszinhaz.monitor.request-timeout=60000
vigszinhaz.notification.recipient=nagavo@gmail.com
vigszinhaz.notification.subject=V\u00edgsz\u00ednh\u00e1z - \u00faj id\u0151pont
vigszinhaz.notification.text=\u00daj id\u0151pont \u00e9rhet\u0151 el: